### ISSUE TITLE
TypeError: m._init is not a function

### ISSUE THREAD

**Issue by ajit3259** [PacktPublishing/Learn-WebAssembly#1]
chapter-06-interact-with-js
While serving the js-with-glue.html
**the init() function call seem to produce TypeError**

I generated the the js file with commands given in readme.md under section Interaction with Glue Code
![Screenshot from 2019-06-06 12-22-46](https://user-images.githubusercontent.com/35459327/59012737-e6f62700-8855-11e9-8af1-fd830d0afb75.png)

I am using 
Ubuntu 18.04
Firefox 67.0

**Comment by mikerourke** [comment]
Hi Ajit, I apologize for the delayed response, I wasn't getting GitHub notifications! So I tried the code out on a newer MacBook Air with a fresh EMSDK install and it's working for me. I suspect the issue may be due to breaking changes in the EMSDK version. Could you try running the following commands within your `emsdk` directory?

```bash
./emsdk install sdk-1.38.15-64bit

./emsdk activate sdk-1.38.15-64bit
```

After it finishes up, run the `source ./emsdk_env.sh` command, the re-run the `make js-with-glue` command inside the the `chapter-06-interact-with-js` directory.

Please let me know if that fixed the issue. Thanks!

**Comment by mikerourke** [comment]
@ajit3259 Did my suggestion end up fixing your issue?
