### ISSUE TITLE
Chapter 5 without-glue.html fails

### ISSUE THREAD

**Issue by bastet77** [PacktPublishing/Learn-WebAssembly#2]
Get the following message in the console when I try to run example.

without-glue:1 Uncaught (in promise) LinkError: WebAssembly.instantiate(): Import #0 module="env" function="__memory_base" error: global import must be a number or WebAssembly.Global object

Chrome: Version 75.0.3770.100 (Official Build) (64-bit)
Windows 10

**Comment by mikerourke** [comment]
@bastet77 I believe your issue is caused by using a newer version of the EMSDK. There was some breaking changes in a version that came out after the book was published. Could you try running the following command in your `emsdk` directory?:

```
emsdk install sdk-1.38.15-64bit

emsdk activate —global sdk-1.38.15-64bit
```

Once that's finished, run the following command to setup the environment:
```
emsdk_env.bat
```

Then `cd` into the  `/chapter-05-create-load-module` directory and try re-running the `make without-glue` command. Let me know if that fixes your issue. If not, I'm traveling right now so I don't have a laptop with a Windows VM, but I'll be home on Tuesday so I can troubleshoot it then.

**Comment by lumiit-adam** [comment]
I also met this problem. My platform is windows 10 and emscripten 1.38.31. I changed 2 places in the codes of this example.

load-wasm.js:

```
const getDefaultEnv = () => ({
  __memory_base : 0,
  __table_base : 0,
  memory: new WebAssembly.Memory({ initial: 256 }),
  table: new WebAssembly.Table({ initial: 0, element: 'anyfunc' }),
  abort: console.log
});
```
and the cmd

`emcc without-glue.c -Os -s WASM=1 -s SIDE_MODULE=1 -s EXPORT_ALL=1 -o without-glue.wasm`

I check the document of emcc, by default the emcc remove the dead code when compile, add " -s EXPORT_ALL=1" to force the symbols totally export. Otherwize, the C functions won't be export.

**Comment by ManikandanKurup-Packt** [comment]
Please reopen if the issue persists.
