### ISSUE TITLE
caught (in promise) TypeError: WebAssembly.instantiate(): Import #3 module="GOT.mem" error: module is not an object or function

### ISSUE THREAD

**Issue by HyungChan71** [PacktPublishing/Learn-WebAssembly#55]
hello.
I'm running through examples from Learn WebAssembly to get a grip on the concept of WebAssembly.

During execution, an error occurs in Chapter 5 without-glue, but I do not know how to solve it.
help.

The build environment is as follows.

GNU Make 	=> v3.81
CMake 		=> v3.26.3
Node.js		=> v16.16.0
rimraf		=> v5.0.0
OS		=> Window10

Build and run proceeded as follows by referring to README.md.

> emcc without-glue.c -Os -s WASM=1 -s SIDE_MODULE=1 -s BINARYEN_ASYNC_COMPILATION=0 -o without-glue.wasm

without-glue.wasm file created

> serve -l 8080
> http://127.0.0.1:8080/chapter-05-create-load-module/without-glue.html

When I run the server and open html in the chrome browser, an error occurs in the browser console.

==> caught (in promise) TypeError: WebAssembly.instantiate(): Import #3 module="GOT.mem" error: module is not an object or function

**Comment by mikerourke** [comment]
@HyungChan71 I was able to get it working, but it's going to require some changes to the versions of the tooling you have installed. Since the book is almost 5 years old and Emscripten/WebAssembly has gone through a lot of changes, the current versions of what you have installed won't work. Please follow the instructions below to get it working:

## Python

1. Uninstall Python v3.11.3
2. Download Python v3.7.1 from [this page](https://www.python.org/downloads/release/python-371/)
   - Note that you should download the `Windows x86-64 executable installer` file
3. Install Python v3.7.1
   - **Make sure to check the option in the installer screen to add Python to `PATH`**

## emsdk

1. Open a command prompt and `cd` into where you cloned the `emsdk` repository:
```cmd
cd <path to emsdk repository>
```
2. Run the following command:
```cmd
git checkout 0b2084f40444818e4478a93009e2dd4426e14762
```
3. While in the `emsdk` directory, run the following command to install the version of `emsdk` used in the book:
```cmd
emsdk install sdk-fastcomp-1.38.15-64bit
```
4. Once complete, run the following command to activate the version you just installed:
```cmd
emsdk activate sdk-fastcomp-1.38.15-64bit
```

## Post-Installation

1. Run the following command from the `emsdk` repository directory to update the environment variables:
 ```cmd
emsdk_env.bat
```
2. `cd` into the `chapter-05-create-load-module` within `Learn-WebAssembly` repository and run the command to build `without-glue`:
```cmd
make without-glue
```
3. Once built, run `serve .` in the directory and navigate to `http://localhost:3000/without-glue.html` in the browser, and it should be working correctly
   - Note that the port number may be different, but the `serve` command will log the URL out to the console

**Comment by HyungChan71** [comment]
Thank you.
Thanks to that, I was able to run the program and see the results.
